name: CI CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101    
    - name: Build
      run: dotnet build --configuration Release
  dev-deploy:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    name: Deploy to dev
    needs: build
    environment:
      name: Dev
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet publish 'GitHubEnvDemo.Web\GitHubEnvDemo.Web.csproj' --configuration Release -o 'publish/app'
    - name: Deploy to azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: env-demo-dev
        publish-profile: ${{ secrets.DEV_PUBLISH_PROFILE }}
        package: 'publish/app'
  prd-deploy:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    name: Deploy to prd
    needs: build
    environment:
      name: Prd
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet publish 'GitHubEnvDemo.Web\GitHubEnvDemo.Web.csproj' --configuration Release -o 'publish/app'
    - name: Deploy to azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: env-demo-prd
        publish-profile: ${{ secrets.PRD_PUBLISH_PROFILE }}
        package: 'publish/app'